name: ibrainstorm
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9579484721180052
title: 'The site that helps you achieve your goals!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#888888'
    - '#ffffff'
    - '#ee2c0f'
    - '#1210f3'
  brandStrength: 0.9059366409201175
  lightness: 0.17360784276388586
  saturation: 0.24359703552909195
  rhythmicContrast: 0.999062180519104
purpose: []
