name: ibrainstorm
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9579484721180052
title: 'The site that helps you achieve your goals!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bbbbbb'
    - '#3d3d3d'
    - '#8b8b8b'
    - '#ffffff'
  brandStrength: 0.1875
  lightness: 0
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
